--drop table
DROP TABLE IF EXISTS MEMBERSHIP;

--create table
CREATE TABLE MEMBERSHIP(
	  ID LONG auto_increment PRIMARY KEY
	, MEMBERSHIP_NAME VARCHAR(20) not null
	, USER_ID VARCHAR(255) not null
	, POINT INT default(0)
);

--insert data
INSERT INTO MEMBERSHIP(MEMBERSHIP_NAME, USER_ID, POINT) VALUES('네이버', 'woo12', 10000);
INSERT INTO MEMBERSHIP(MEMBERSHIP_NAME, USER_ID, POINT) VALUES('라인', 'yoon34', 80000);